[font]
size = 17.5

[font.normal]
family = "Zed Mono"

[window]
opacity = 0.8

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

# Gruvbox Material
# [colors.primary]
# background = '#1d2021'
# foreground = '#d4be98'
#
# [colors.normal]
# black   = '#32302f'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#d8a657'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#d4be98'
#
# [colors.bright]
# black   = '#62605f'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#d8a657'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#d4be98'
