editor = "/usr/bin/env nvim"

[bootstrap]
linux.fedora = [
  "sudo dnf upgrade --refresh -y",
  "sudo dnf check",
  "sudo dnf autoremove",
  "sudo fwupdmgr get-devices",
  "sudo fwupdmgr refresh --force",
  "sudo fwupdmgr get-updates",
  "sudo fwupdmgr update",
  "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo",
  "flatpak update -y",
  "flatpak install flathub org.libreoffice.LibreOffice com.spotify.Client com.discordapp.Discord -y",
  "sudo dnf install -y curl cabextract xorg-x11-font-utils fontconfig",
  "sudo rpm -i https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm",
]

[update]
linux.fedora = [
  "sudo dnf upgrade --refresh -y",
  "flatpak update -y"
]

[alacritty]
location = "$HOME/.config/alacritty"
main = "alacritty.toml"

[bin]
location = "$HOME/bin"
main = "tmuxsessionizer"

[foot]
location = "$HOME/.config/foot"
main = "foot.ini"

[i3]
location = "$HOME/.config/i3"
main = "config"

[keyboard]
location = "$HOME/.config/xkb"
main = "programmers-colemak.xkb"

[nvim]
location = "$HOME/.config/nvim"
main = "init.lua"

[picom]
location = "$HOME/.config/picom"
main = "picom.conf"

[polybar]
location = "$HOME/.config/polybar"
main = "config.ini"

[starship]
location = [{src = "starship.toml", dest = "$HOME/.config/starship.toml"}]
main = "starship.toml"

[tmux]
location = [{src = "tmux.conf", dest = "$HOME/.tmux.conf"}]
main = "tmux.conf"

[sway]
location = "$HOME/.config/sway"
main = "config"

[vim]
location = [{src="vimrc", dest="$HOME/.vimrc"}]
main = "vimrc"

[waybar]
location = "$HOME/.config/waybar"
main = "config.jsonc"

[zsh]
location = [{src = "zshrc", dest = "$HOME/.zshrc" }]
main = "zshrc"
