# ZSH Config

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# Enironment Variables
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin

# Paths
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:$HOME/anaconda3/bin
export PATH=$PATH:$HOME/.bun/bin
export PATH=$PATH:$HOME/bin

# Keybindings
bindkey -s '^t' "tmuxsessionizer\n"
bindkey -s '^w' "cd ~/dotfiles;  ds edit \$\(ds edit \| fzf\); cd - > /dev/null\n"
bindkey "\e[1;3C" forward-word
bindkey "\e[1;3D" backward-word

# Plugins
source ~/.zsh-plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source ~/.zsh-plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

# Starship
eval "$(starship init zsh)"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/try/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/try/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/try/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/try/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# pnpm
export PNPM_HOME="/home/try/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
