bindkey -e

HISTSIZE=1000000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
setopt appendhistory
setopt sharehistory

alias ls=eza
alias claude='claude --allow-dangerously-skip-permissions'
alias review='nvim -c "DiffviewOpen"'

export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin

# export PATH=$PATH:/opt/homebrew/bin
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/Library/Python/3.9/bin
export PATH=$PATH:$HOME/.cargo/bin

bindkey '\e[1;3D' backward-word
bindkey '\e[1;3C' forward-word

bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# Starship
eval "$(starship init zsh)"

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zsh-users/zsh-syntax-highlighting \
    zsh-users/zsh-autosuggestions \
    zsh-users/zsh-completions \

### End of Zinit's installer chunk

# bun completions
[ -s "/Users/rsaran/.bun/_bun" ] && source "/Users/rsaran/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# fnm
FNM_PATH="/Users/rsaran/Library/Application Support/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="/Users/rsaran/Library/Application Support/fnm:$PATH"
  eval "`fnm env`"
fi

# UV
# source $HOME/.local/bin/env

eval "$(fnm env --use-on-cd --shell zsh)"

# export ANDROID_HOME=$HOME/Library/Android/sdk
# export PATH=$PATH:$ANDROID_HOME/emulator
# export PATH=$PATH:$ANDROID_HOME/platform-tools
# export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"


export EDITOR="nvim"

# . "$HOME/.local/bin/env"
export PATH="/opt/homebrew/opt/postgresql@17/bin:$PATH"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

source $HOME/.local/bin/env

export AIRFLOW_HOME=~/airflow

# Pyspark
export PYSPARK_PYTHON=/Users/rsaran/virtualenvs/spark-env/bin/python
export PYSPARK_DRIVER_PYTHON=/Users/rsaran/virtualenvs/spark-env/bin/python

# Shopify Hydrogen alias to local projects
alias h2='$(npm prefix -s)/node_modules/.bin/shopify hydrogen'

export MINIMAX_API_KEY="sk-cp-ZTkKYLsRdAmlz0c7mkxB_8znnldar_d3Ej5hQQXdXoVqWSuVMK0ahQcIw3F-AIfxJgnvmIdGiv65QM-Wu49fC6UAt0Pn2IWBXxGAiOk3uY5e16ZcoJtW6tU"

# opencode
export PATH=/Users/rsaran/.opencode/bin:$PATH
export PATH="/opt/homebrew/opt/curl/bin:$PATH"
